### ISSUE TITLE
Textable events for Summer Tech

### ISSUE THREAD

**Issue by timparenti** [ABTech/tracker#358]
Textable events should be able to go to a Summer Tech GroupMe instead of the main one, which would keep the main group clear for summertime announcements relevant to fall/spring, discouraging muting.

I'm not sure what implementation details would be desirable.  It might suffice to simply apply this to events within the existing "summer period" (6/1 to 8/9 each year), but perhaps it's better to include the org listed for the event in a heuristic, or maybe it really should be explicitly selectable.

**Comment by DaAwesomeP** [comment]
Closing as #events in Slack can be simply muted during the summer if needed.

**Comment by timparenti** [comment]
Oh, lol, yeah this is a bit easier to handle with Slack and its _channelization_ than it was with plain ol' GroupMe.

+1, thanks for cleaning up around here.
