### ISSUE TITLE
Insufficient privileges to add quote as TiC

### ISSUE THREAD

**Issue by reckert477** [ABTech/tracker#369]
<img width="1314" alt="screen shot 2018-08-28 at 7 48 21 am" src="https://user-images.githubusercontent.com/22248205/44721140-f199b980-aa96-11e8-8542-a8c2966e0140.png">

**Comment by DaAwesomeP** [comment]
I think the way we currently work is that email handlers have access to quotes/invoices and TiC (if not an email handler) has read-only access.
