### ISSUE TITLE
Event Request Form should not be filling in "Email Description" field

### ISSUE THREAD

**Issue by andrewsheng2** [ABTech/tracker#462]
On Tracker, the "Email Description" gets used to automatically populate information and notes that gets sent in a weekly email. We haven't recently used the built in feature of Tracker to send weekly emails so this field doesn't actually do anything, but we should still avoid populating the "Email Description" field with details from the event request.

On that note, we should also rename "Email Description" to be a bit more clear in its purpose, perhaps something like "Weekly Email Info"

**Comment by DaAwesomeP** [comment]
Ah yeah I didn't know that's what that was for. Yeah I'll fix that.

**Comment by DaAwesomeP** [comment]
Fix is live. If you'd like to manually fix the events that this affected that would be great.
