### ISSUE TITLE
Change email of SLICE member who processes invoices

### ISSUE THREAD

**Issue by shannoding** [ABTech/tracker#487]
- Specifically, change all mentions of Kimberly Reynolds or klreynol with SLICE Finance and SLICEfinance
- For the future, have a field perhaps found on the Invoices page sidebar to update the name and email

**Comment by DaAwesomeP** [comment]
This is more difficult than it may seem because Tracker does not have a central settings model, but I will look into it. I think I can making a manageable invoices address book may be the best solution.

**Comment by DaAwesomeP** [comment]
Hmmm, if this is changing to the non-person-specific SLICE finance address, is this likely to ever need to change again?

**Comment by DaAwesomeP** [comment]
Removed klreynol in 8a7fda3733a3cb8a49da6c82bcaae3d0ce4285bc

**Comment by shannoding** [comment]
Sorry to make you do this again :( I don't think you need to change the name on the invoices and email text, just add [yharewoo@andrew.cmu.edu](mailto:yharewoo@andrew.cmu.edu) to the cc
