### ISSUE TITLE
"View Payroll" display whether hours billed for call, show, or strike

### ISSUE THREAD

**Issue by shannoding** [ABTech/tracker#488]
- Currently, billing for call/show/strike creates an additional row in the payroll display table without indicating whether it was from call/show/strike. Perhaps add a new column.

![image](https://user-images.githubusercontent.com/19763542/188904101-de92d226-4b99-417c-8cb2-de510c74b501.png)

**Comment by shannoding** [comment]
https://tracker.abtech.org/events/3648/finance
This comes up on any View Payroll page with the "Allow billing for call/show/strike" enabled. Open an event, click View Payroll on the left sidebar.

**Comment by DaAwesomeP** [comment]
I see. Would it be fine if I simply add the designator to each row instead of 3 new columns? That will match the rest of the UI on other pages.

**Comment by shannoding** [comment]
Yes, that's fine!

**Comment by DaAwesomeP** [comment]
Added in 28a52a036d00ce6af220caf66cc2c9914f2e658f
