### ISSUE TITLE
Show name preview on Tracker Admin

### ISSUE THREAD

**Issue by izhanchang** [ABTech/tracker#513]
Harder to approve time between Workday and Tracker when nicknames are used 

<img width="145" alt="image" src="https://user-images.githubusercontent.com/96501599/230778762-7bc1ce82-cfe9-41e5-94e4-a3fb9bbff36d.png">
 
Can the hover-over preview work here or use some other identifier on the Tracker admin > timecards page?
![image](https://user-images.githubusercontent.com/96501599/230778842-a2b8e961-3e64-4e99-918a-b1b264c16e2c.png)

**Comment by DaAwesomeP** [comment]
Yeah I'll see if I can add the hover feature there.
