### ISSUE TITLE
Allow exec to mark quotes as contracts

### ISSUE THREAD

**Issue by clariseliu** [ABTech/tracker#521]
We recently had a non-HoT try to make a contract for an equipment rental. This person is listed as "Exec" on Tracker. While they were able to make a quote, they could not convert it to a contract. The quick fix was to make the exec member a Head of Tech on tracker, have them convert it to a contract, and revert their role back to Exec. Ideally, all exec members can covert quotes to contracts. The current workaround is not ideal since the HoT role has significantly more permissions than exec.

**Comment by DaAwesomeP** [comment]
Should be an easy fix.

For a better current workaround, a HoT marks a quote as a contract anyone should still be able to edit that contract. So instead of modifying someone's permissions you can simply mark a quote as a contract.

**Comment by maxjkwang** [comment]
> Should be an easy fix.
> 
> For a better current workaround, a HoT marks a quote as a contract anyone should still be able to edit that contract. So instead of modifying someone's permissions you can simply mark a quote as a contract.

We tried it, but if a HoT marks it as a contract, it's read-only for ppl with exec permissions. Similar for invoices.
