### ISSUE TITLE
"Appliable" field missing from event_role

### ISSUE THREAD

**Issue by NoRePercussions** [ABTech/tracker#530]
Despite being [referenced repeatedly](https://github.com/search?q=repo:ABTech/tracker%20appliable&type=code) and [in the schema](https://github.com/ABTech/tracker/blob/52d7f67deade6ffb82b491fa0caf346d7dec1629/db/schema.rb#L151), there doesn't seem to be a definition for `:appliable` in the [event_roles model](https://github.com/ABTech/tracker/blob/52d7f67deade6ffb82b491fa0caf346d7dec1629/app/models/event_role.rb).

**Comment by DaAwesomeP** [comment]
In Rails schema attributes do not have to be mentioned in the model unless you need to perform/add some non-default methods/functionality to the attribute.
